# Generated by Django 5.1.1 on 2024-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0003_alter_userincome_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={},
        ),
        migrations.AlterField(
            model_name='userincome',
            name='amount',
            field=models.FloatField(),
        ),
    ]
