# Generated by Django 5.1.2 on 2024-10-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0004_alter_userincome_options_alter_userincome_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date']},
        ),
    ]
